
<?php
// admin/view-trips.php
require_once '../config/db.php';
require_admin();

$page_title = 'View All Trips';

// Handle delete action
if (isset($_GET['action']) && $_GET['action'] == 'delete' && isset($_GET['id'])) {
    $trip_id_to_delete = filter_var($_GET['id'], FILTER_VALIDATE_INT);
    if ($trip_id_to_delete) {
        $stmt = $pdo->prepare("DELETE FROM trips WHERE id = ?");
        $stmt->execute([$trip_id_to_delete]);
        $_SESSION['feedback'] = ['type' => 'success', 'message' => 'Trip #' . $trip_id_to_delete . ' has been deleted.'];
        header('Location: view-trips.php');
        exit();
    }
}


// Fetch all trips with user information
$stmt = $pdo->query("
    SELECT t.*, u.name as user_name
    FROM trips t
    JOIN users u ON t.user_id = u.id
    ORDER BY t.created_at DESC
");
$trips = $stmt->fetchAll();

include 'header.php';
?>

<?php if (isset($_SESSION['feedback'])): ?>
    <div class="alert alert-<?= $_SESSION['feedback']['type'] ?>"><?= $_SESSION['feedback']['message'] ?></div>
    <?php unset($_SESSION['feedback']); ?>
<?php endif; ?>

<div class="card">
    <div class="card-header">
        <h3>All Generated Trips</h3>
    </div>
    <div class="table-responsive">
        <table>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>User</th>
                    <th>Destination</th>
                    <th>Duration</th>
                    <th>Created On</th>
                    <th>Downloaded</th>
                    <th>Shared</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                <?php if (empty($trips)): ?>
                    <tr><td colspan="8">No trips have been generated by users yet.</td></tr>
                <?php else: ?>
                    <?php foreach ($trips as $trip): ?>
                        <tr>
                            <td><?= $trip['id'] ?></td>
                            <td><?= htmlspecialchars($trip['user_name']) ?></td>
                            <td><?= htmlspecialchars($trip['city']) ?></td>
                            <td><?= $trip['days'] ?> days</td>
                            <td><?= date('M d, Y H:i', strtotime($trip['created_at'])) ?></td>
                            <td><span class="status-badge <?= $trip['is_downloaded'] ? 'status-approved' : 'status-pending_generation' ?>"><?= $trip['is_downloaded'] ? 'Yes' : 'No' ?></span></td>
                            <td><span class="status-badge <?= $trip['is_shared'] ? 'status-approved' : 'status-pending_generation' ?>"><?= $trip['is_shared'] ? 'Yes' : 'No' ?></span></td>
                            <td class="actions">
                                <a href="#" class="btn btn-sm btn-primary btn-view-trip" data-trip-content="<?= htmlspecialchars($trip['ai_trip_text']) ?>">View</a>
                                <a href="?action=delete&id=<?= $trip['id'] ?>" class="btn btn-sm btn-danger btn-delete-confirm" data-confirm-message="Are you sure you want to delete this trip?">Delete</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                <?php endif; ?>
            </tbody>
        </table>
    </div>
</div>

<!-- Modal for viewing trip content -->
<div id="trip-modal" class="modal" style="display:none;">
    <div class="modal-content">
        <span class="modal-close">&times;</span>
        <h3>Trip Itinerary</h3>
        <div class="trip-plan" id="modal-trip-content"></div>
    </div>
</div>

<style>
.modal{display:none;position:fixed;z-index:1000;left:0;top:0;width:100%;height:100%;overflow:auto;background-color:rgba(0,0,0,0.6)}
.modal-content{background-color:#fefefe;margin:10% auto;padding:20px;border:1px solid #888;width:80%;max-width:700px;border-radius:8px;position:relative}
.modal-close{color:#aaa;float:right;font-size:28px;font-weight:bold;cursor:pointer}
.modal-close:hover,.modal-close:focus{color:black;text-decoration:none}
</style>

<script>
document.addEventListener('DOMContentLoaded', function() {
    const modal = document.getElementById('trip-modal');
    const modalContent = document.getElementById('modal-trip-content');
    const closeBtn = document.querySelector('.modal-close');

    document.querySelectorAll('.btn-view-trip').forEach(button => {
        button.addEventListener('click', function(e) {
            e.preventDefault();
            const content = this.getAttribute('data-trip-content');
            modalContent.innerHTML = content.replace(/\n/g, '<br>');
            modal.style.display = 'block';
        });
    });

    closeBtn.onclick = function() {
        modal.style.display = 'none';
    }

    window.onclick = function(event) {
        if (event.target == modal) {
            modal.style.display = 'none';
        }
    }
});
</script>

<?php include 'footer.php'; ?>
